install.packages("caret", dependencies = TRUE)
install.packages("randomForest")
library(caret)
library(randomForest)
setwd("~/Data/Titanic")
trainSet <- read.table("train.csv", sep = ",", header = TRUE)
View(trainSet)
testSet <- read.table("test.csv", sep = ",", header = TRUE)
View(testSet)
head(trainSet)
head(testSet)
table(trainSet[c("Survived","Pclass")])
install.packages("fields")
library(fields)
bplot.xy(trainSet$Survived,trainSet$Age)
bplot.xy(trainSet$Survived,trainSet$Pclass)
summary(trainSet$Age)
bplot.xy(trainSet$Survived,trainSet$Fare)
summary(trainSet$Fare)
trainSet$Survived <- factor(trainSet$Survived)
set.seed(42)
model <- train(Survived ~ Pclass + Sex + SibSp + Embarked + Parch + Fare, data = trainSet, method = "rf", trControl = trainControl(method = "cv", number = 5))
model
testSet$Survived <- predict(model, newdata = testSet)
summary(testSet)
mean(testSet$Fare)
mean(testSet$Fare, na.rm = TRUE)
testSet$Fare <- ifelse(is.na(testSet$Fare), mean(testSet$Fare, na.rm = TRUE), testSet$Fare)
summary(testSet)
testSet$Survived <- predict(model, newdata = testSet)
submission <- testSet[c("PassengerId","Survived")]
write.table(submission, file="submission.csv", col.names = TRUE, row.names = FALSE, sep = ",")
